on: [push]

name: build

jobs:
  check:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Neovim
        shell: bash
        run: |
            wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb -O /tmp/nvim.deb
            sudo dpkg -i /tmp/nvim.deb

      - name: Install plenary.nvim (for testing)
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: Run cargo clippy (workspace)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace

      - name: Run cargo check (workspace)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace

      - name: Run cargo build (workspace)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
